# -*- coding: utf-8 -*-
"""mood_journal_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9Un0E7uwPglOm6doqjWLTv2sEiI9SYH
"""

import datetime

def mood_journal():
    print("🧘‍♀️ Welcome to your Mood Journal!")
    mood = input("How are you feeling today (happy, sad, anxious, etc)? ")
    note = input("Write a short note about your day: ")

    # Get the current date and time
    now = datetime.datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    # Format the journal entry
    entry = f"\n[{timestamp}]\nMood: {mood}\nNote: {note}\n{'-'*40}\n"

    # Write to a file
    with open("mood_log.txt", "a") as file:
        file.write(entry)

    print("\n💾 Your entry has been saved! See you tomorrow, bestie 💖")

# Run the function
mood_journal()